Update dotnetCLI.yml

diff --git a/.github/workflows/dotnetCLI.yml b/.github/workflows/dotnetCLI.yml
--- a/.github/workflows/dotnetCLI.yml
+++ b/.github/workflows/dotnetCLI.yml
@@ -2,7 +2,6 @@
 # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
 
 name: Unit Test and Build CLI
-
 on:
   push:
     branches: [ "develop" ]
@@ -10,19 +9,37 @@ on:
     branches: [ "develop" ]
 
 jobs:
-  build:
-
+  build-test:
+    name: Build & Test
     runs-on: ubuntu-latest
-
     steps:
-    - uses: actions/checkout@v3
-    - name: Setup .NET
-      uses: actions/setup-dotnet@v3
-      with:
-        dotnet-version: 6.0.x
-    - name: Restore dependencies
-      run: dotnet restore
-    - name: Build
-      run: dotnet build --no-restore
-    - name: Test
-      run: dotnet test --no-build --verbosity normal
+      - uses: actions/checkout@v3     # checkout the repo
+      - name: Setup .NET
+        uses: actions/setup-dotnet@v3
+        with:
+          dotnet-version: 6.0.x
+      - name: Install Coverlet
+        run: cd unitTests && dotnet add package coverlet.msbuild
+      - name: Navigate to UML
+        run: cd UML
+      - name: Test
+        run: dotnet test UML /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --logger "trx;LogFileName=test-results.trx" 
+      - name: Build
+        run: dotnet build UML
+      - name: Dir
+        run: cd unitTests && ls
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Dotnet Tests            # Name of the check run which will be created
+          path: unitTests/TestResults/test-results.trx   # Path to test results
+          reporter: dotnet-trx        # Format of test results
+      - name: CodeCov
+        uses: codecov/codecov-action@v3
+        with:
+          files: ./unitTests/coverage.opencover.xml # optional
+          flags: unittests # optional
+          name: codecov-umbrella # optional
+          fail_ci_if_error: true # optional (default = false)
+          verbose: true # optional (default = false)
