Update dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -7,18 +7,37 @@ on:
     branches: [ "develop" ]
 
 jobs:
-  build:
-
+  build-test:
+    name: Build & Test
     runs-on: ubuntu-latest
-
     steps:
-    - uses: actions/checkout@v3
-    - name: Setup .NET
-      uses: actions/setup-dotnet@v3
-      with:
-        dotnet-version: 6.0.x
-    - name: Dir
-      run: cd UML && pwd
-    - name: Build
-      run: dotnet build UML
+      - uses: actions/checkout@v3     # checkout the repo
+      - name: Setup .NET
+        uses: actions/setup-dotnet@v3
+        with:
+          dotnet-version: 6.0.x
+      - name: Install Coverlet
+        run: cd unitTests && dotnet add package coverlet.msbuild
+      - name: Navigate to UML
+        run: cd UML
+      - name: Build
+        run: dotnet build UML
+      - name: Test
+        run: dotnet test unitTests --logger "trx;LogFileName=test-results.trx" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
+      - name: Dir
+        run: cd unitTests && ls
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Dotnet Tests            # Name of the check run which will be created
+          path: unitTests/TestResults/test-results.trx   # Path to test results
+          reporter: dotnet-trx        # Format of test results
+      - name: CodeCov
+        run: curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov && ./codecov -R unitTests
+        
+        
+
+
+
 
