Update dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -7,20 +7,30 @@ on:
     branches: [ "develop" ]
 
 jobs:
-  build:
-
+  build-test:
+    name: Build & Test
     runs-on: ubuntu-latest
-
     steps:
-    - uses: actions/checkout@v3
-    - name: Setup .NET
-      uses: actions/setup-dotnet@v3
-      with:
-        dotnet-version: 6.0.x
-    - name: Dir
-      run: cd UML && pwd
-    - name: Build
-      run: dotnet build UML
-    - name: Test
-      run: dotnet test unitTests --list-tests --no-restore --verbosity normal
+      - uses: actions/checkout@v2     # checkout the repo
+      - run: npm ci                   # install packages
+      - run: npm test                 # run tests (configured to use jest-junit reporter)
+      
+      - name: Setup .NET
+        uses: actions/setup-dotnet@v3
+        with:
+          dotnet-version: 6.0.x
+      - name: Dir
+        run: cd UML && pwd
+      - name: Build
+        run: dotnet build UML
+      - name: Test
+        run: dotnet test unitTests --logger "trx;LogFileName=test-results.trx"
+
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Dotnet Tests            # Name of the check run which will be created
+          path: test-results.trx    # Path to test results
+          reporter: dotnet-trx        # Format of test results
 
